
package service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SABService", targetNamespace = "http://Service/", wsdlLocation = "http://dry-island-4611.herokuapp.com/SABService?wsdl")
public class SABService_Service
    extends Service
{

    private final static URL SABSERVICE_WSDL_LOCATION;
    private final static WebServiceException SABSERVICE_EXCEPTION;
    private final static QName SABSERVICE_QNAME = new QName("http://Service/", "SABService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://dry-island-4611.herokuapp.com/SABService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SABSERVICE_WSDL_LOCATION = url;
        SABSERVICE_EXCEPTION = e;
    }

    public SABService_Service() {
        super(__getWsdlLocation(), SABSERVICE_QNAME);
    }

    public SABService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), SABSERVICE_QNAME, features);
    }

    public SABService_Service(URL wsdlLocation) {
        super(wsdlLocation, SABSERVICE_QNAME);
    }

    public SABService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SABSERVICE_QNAME, features);
    }

    public SABService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SABService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SABService
     */
    @WebEndpoint(name = "SABServicePort")
    public SABService getSABServicePort() {
        return super.getPort(new QName("http://Service/", "SABServicePort"), SABService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SABService
     */
    @WebEndpoint(name = "SABServicePort")
    public SABService getSABServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://Service/", "SABServicePort"), SABService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SABSERVICE_EXCEPTION!= null) {
            throw SABSERVICE_EXCEPTION;
        }
        return SABSERVICE_WSDL_LOCATION;
    }

}
