
package org.chamerling.heroku.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloService", targetNamespace = "http://service.heroku.chamerling.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloService {


    /**
     * 
     * @return
     *     returns java.util.List<org.chamerling.heroku.service.Content>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "loadPost", targetNamespace = "http://service.heroku.chamerling.org/", className = "org.chamerling.heroku.service.LoadPost")
    @ResponseWrapper(localName = "loadPostResponse", targetNamespace = "http://service.heroku.chamerling.org/", className = "org.chamerling.heroku.service.LoadPostResponse")
    public List<Content> loadPost();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "nyoba", targetNamespace = "http://service.heroku.chamerling.org/", className = "org.chamerling.heroku.service.Nyoba")
    @ResponseWrapper(localName = "nyobaResponse", targetNamespace = "http://service.heroku.chamerling.org/", className = "org.chamerling.heroku.service.NyobaResponse")
    public String nyoba();

    /**
     * 
     * @param id
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "restoreDeletedPost", targetNamespace = "http://service.heroku.chamerling.org/", className = "org.chamerling.heroku.service.RestoreDeletedPost")
    @ResponseWrapper(localName = "restoreDeletedPostResponse", targetNamespace = "http://service.heroku.chamerling.org/", className = "org.chamerling.heroku.service.RestoreDeletedPostResponse")
    public boolean restoreDeletedPost(
        @WebParam(name = "id", targetNamespace = "")
        String id);

    /**
     * 
     * @param judul
     * @param konten
     * @param tanggal
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addPost", targetNamespace = "http://service.heroku.chamerling.org/", className = "org.chamerling.heroku.service.AddPost")
    @ResponseWrapper(localName = "addPostResponse", targetNamespace = "http://service.heroku.chamerling.org/", className = "org.chamerling.heroku.service.AddPostResponse")
    public boolean addPost(
        @WebParam(name = "judul", targetNamespace = "")
        String judul,
        @WebParam(name = "tanggal", targetNamespace = "")
        String tanggal,
        @WebParam(name = "konten", targetNamespace = "")
        String konten);

    /**
     * 
     * @return
     *     returns java.util.List<org.chamerling.heroku.service.User>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "loadUser", targetNamespace = "http://service.heroku.chamerling.org/", className = "org.chamerling.heroku.service.LoadUser")
    @ResponseWrapper(localName = "loadUserResponse", targetNamespace = "http://service.heroku.chamerling.org/", className = "org.chamerling.heroku.service.LoadUserResponse")
    public List<User> loadUser();

    /**
     * 
     * @param judul
     * @param id
     * @param konten
     * @param tanggal
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "editPost", targetNamespace = "http://service.heroku.chamerling.org/", className = "org.chamerling.heroku.service.EditPost")
    @ResponseWrapper(localName = "editPostResponse", targetNamespace = "http://service.heroku.chamerling.org/", className = "org.chamerling.heroku.service.EditPostResponse")
    public boolean editPost(
        @WebParam(name = "id", targetNamespace = "")
        String id,
        @WebParam(name = "judul", targetNamespace = "")
        String judul,
        @WebParam(name = "tanggal", targetNamespace = "")
        String tanggal,
        @WebParam(name = "konten", targetNamespace = "")
        String konten);

    /**
     * 
     * @param id
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "publishPost", targetNamespace = "http://service.heroku.chamerling.org/", className = "org.chamerling.heroku.service.PublishPost")
    @ResponseWrapper(localName = "publishPostResponse", targetNamespace = "http://service.heroku.chamerling.org/", className = "org.chamerling.heroku.service.PublishPostResponse")
    public boolean publishPost(
        @WebParam(name = "id", targetNamespace = "")
        String id);

    /**
     * 
     * @param username
     * @param email
     * @param name
     * @param role
     * @param password
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addUser", targetNamespace = "http://service.heroku.chamerling.org/", className = "org.chamerling.heroku.service.AddUser")
    @ResponseWrapper(localName = "addUserResponse", targetNamespace = "http://service.heroku.chamerling.org/", className = "org.chamerling.heroku.service.AddUserResponse")
    public boolean addUser(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "password", targetNamespace = "")
        String password,
        @WebParam(name = "email", targetNamespace = "")
        String email,
        @WebParam(name = "role", targetNamespace = "")
        String role,
        @WebParam(name = "name", targetNamespace = "")
        String name);

    /**
     * 
     * @param id
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deletePost", targetNamespace = "http://service.heroku.chamerling.org/", className = "org.chamerling.heroku.service.DeletePost")
    @ResponseWrapper(localName = "deletePostResponse", targetNamespace = "http://service.heroku.chamerling.org/", className = "org.chamerling.heroku.service.DeletePostResponse")
    public boolean deletePost(
        @WebParam(name = "id", targetNamespace = "")
        String id);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "load", targetNamespace = "http://service.heroku.chamerling.org/", className = "org.chamerling.heroku.service.Load")
    @ResponseWrapper(localName = "loadResponse", targetNamespace = "http://service.heroku.chamerling.org/", className = "org.chamerling.heroku.service.LoadResponse")
    public String load(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param id
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "unPublishPost", targetNamespace = "http://service.heroku.chamerling.org/", className = "org.chamerling.heroku.service.UnPublishPost")
    @ResponseWrapper(localName = "unPublishPostResponse", targetNamespace = "http://service.heroku.chamerling.org/", className = "org.chamerling.heroku.service.UnPublishPostResponse")
    public boolean unPublishPost(
        @WebParam(name = "id", targetNamespace = "")
        String id);

}
