
package org.chamerling.heroku.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BlogServiceImplService", targetNamespace = "http://service.heroku.chamerling.org/", wsdlLocation = "http://not-a-simple-blog.herokuapp.com/BlogService?wsdl")
public class BlogServiceImplService
    extends Service
{

    private final static URL BLOGSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException BLOGSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName BLOGSERVICEIMPLSERVICE_QNAME = new QName("http://service.heroku.chamerling.org/", "BlogServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://not-a-simple-blog.herokuapp.com/BlogService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BLOGSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        BLOGSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public BlogServiceImplService() {
        super(__getWsdlLocation(), BLOGSERVICEIMPLSERVICE_QNAME);
    }

    public BlogServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BLOGSERVICEIMPLSERVICE_QNAME, features);
    }

    public BlogServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, BLOGSERVICEIMPLSERVICE_QNAME);
    }

    public BlogServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BLOGSERVICEIMPLSERVICE_QNAME, features);
    }

    public BlogServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BlogServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BlogService
     */
    @WebEndpoint(name = "BlogServiceImplPort")
    public BlogService getBlogServiceImplPort() {
        return super.getPort(new QName("http://service.heroku.chamerling.org/", "BlogServiceImplPort"), BlogService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BlogService
     */
    @WebEndpoint(name = "BlogServiceImplPort")
    public BlogService getBlogServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.heroku.chamerling.org/", "BlogServiceImplPort"), BlogService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BLOGSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw BLOGSERVICEIMPLSERVICE_EXCEPTION;
        }
        return BLOGSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
