
package simpleblog.heroku.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SimpleblogService", targetNamespace = "http://service.heroku.simpleblog/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SimpleblogService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<simpleblog.heroku.service.Post>
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPostList", targetNamespace = "http://service.heroku.simpleblog/", className = "simpleblog.heroku.service.GetPostList")
    @ResponseWrapper(localName = "getPostListResponse", targetNamespace = "http://service.heroku.simpleblog/", className = "simpleblog.heroku.service.GetPostListResponse")
    public List<Post> getPostList(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0)
        throws IOException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<simpleblog.heroku.service.Comment>
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCommentList", targetNamespace = "http://service.heroku.simpleblog/", className = "simpleblog.heroku.service.GetCommentList")
    @ResponseWrapper(localName = "getCommentListResponse", targetNamespace = "http://service.heroku.simpleblog/", className = "simpleblog.heroku.service.GetCommentListResponse")
    public List<Comment> getCommentList(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0)
        throws IOException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns simpleblog.heroku.service.Post
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPost", targetNamespace = "http://service.heroku.simpleblog/", className = "simpleblog.heroku.service.GetPost")
    @ResponseWrapper(localName = "getPostResponse", targetNamespace = "http://service.heroku.simpleblog/", className = "simpleblog.heroku.service.GetPostResponse")
    public Post getPost(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0)
        throws IOException_Exception
    ;

}
