
package simpleblog.heroku.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SimpleblogServiceImplService", targetNamespace = "http://service.heroku.simpleblog/", wsdlLocation = "http://if3110-iii-25-simple-blog.herokuapp.com/SimpleblogService?wsdl")
public class SimpleblogServiceImplService
    extends Service
{

    private final static URL SIMPLEBLOGSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException SIMPLEBLOGSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName SIMPLEBLOGSERVICEIMPLSERVICE_QNAME = new QName("http://service.heroku.simpleblog/", "SimpleblogServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://if3110-iii-25-simple-blog.herokuapp.com/SimpleblogService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SIMPLEBLOGSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        SIMPLEBLOGSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public SimpleblogServiceImplService() {
        super(__getWsdlLocation(), SIMPLEBLOGSERVICEIMPLSERVICE_QNAME);
    }

    public SimpleblogServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SIMPLEBLOGSERVICEIMPLSERVICE_QNAME, features);
    }

    public SimpleblogServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SIMPLEBLOGSERVICEIMPLSERVICE_QNAME);
    }

    public SimpleblogServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SIMPLEBLOGSERVICEIMPLSERVICE_QNAME, features);
    }

    public SimpleblogServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SimpleblogServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SimpleblogService
     */
    @WebEndpoint(name = "SimpleblogServiceImplPort")
    public SimpleblogService getSimpleblogServiceImplPort() {
        return super.getPort(new QName("http://service.heroku.simpleblog/", "SimpleblogServiceImplPort"), SimpleblogService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SimpleblogService
     */
    @WebEndpoint(name = "SimpleblogServiceImplPort")
    public SimpleblogService getSimpleblogServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.heroku.simpleblog/", "SimpleblogServiceImplPort"), SimpleblogService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SIMPLEBLOGSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw SIMPLEBLOGSERVICEIMPLSERVICE_EXCEPTION;
        }
        return SIMPLEBLOGSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
