
package com.github.fawwaz.heroku.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ApiImplService", targetNamespace = "http://service.heroku.fawwaz.github.com/", wsdlLocation = "http://tubes3wbd.herokuapp.com/Api?wsdl")
public class ApiImplService
    extends Service
{

    private final static URL APIIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException APIIMPLSERVICE_EXCEPTION;
    private final static QName APIIMPLSERVICE_QNAME = new QName("http://service.heroku.fawwaz.github.com/", "ApiImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://tubes3wbd.herokuapp.com/Api?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        APIIMPLSERVICE_WSDL_LOCATION = url;
        APIIMPLSERVICE_EXCEPTION = e;
    }

    public ApiImplService() {
        super(__getWsdlLocation(), APIIMPLSERVICE_QNAME);
    }

    public ApiImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), APIIMPLSERVICE_QNAME, features);
    }

    public ApiImplService(URL wsdlLocation) {
        super(wsdlLocation, APIIMPLSERVICE_QNAME);
    }

    public ApiImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, APIIMPLSERVICE_QNAME, features);
    }

    public ApiImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ApiImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Api
     */
    @WebEndpoint(name = "ApiImplPort")
    public Api getApiImplPort() {
        return super.getPort(new QName("http://service.heroku.fawwaz.github.com/", "ApiImplPort"), Api.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Api
     */
    @WebEndpoint(name = "ApiImplPort")
    public Api getApiImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.heroku.fawwaz.github.com/", "ApiImplPort"), Api.class, features);
    }

    private static URL __getWsdlLocation() {
        if (APIIMPLSERVICE_EXCEPTION!= null) {
            throw APIIMPLSERVICE_EXCEPTION;
        }
        return APIIMPLSERVICE_WSDL_LOCATION;
    }

}
